### ISSUE TITLE
Branch Universal Links

### ISSUE THREAD

**Issue by PaitoAnderson** [BranchMetrics/Deferred-Deep-Linking-Public-API#11]
Can this API be used to generate Branch Universal Links?

**Comment by aaustin** [comment]
Yessir - Once you've configured universal links in the app settings on the Branch dashboard, every link created should be 'Universalized'! Happy linking

**Comment by aaustin** [comment]
Closing for now

**Comment by PaitoAnderson** [comment]
Thanks for the quick response @aaustin! I have always had Universal Links enabled in the Branch Dashboard, however the links I am getting back are like this: https://bnc.lt/l/xxxxxxxxxx.

![branchdashboard](https://cloud.githubusercontent.com/assets/4108718/11719740/1a3489a4-9f2a-11e5-86da-71474929facd.jpg)

**Comment by aaustin** [comment]
Arrrr - legacy stuff. Can you insert 'sdk':'api' into the postbody? Let me see if I can remove that restriction in the next few days.

**Comment by PaitoAnderson** [comment]
So cool! That worked! Happy linking to you as well :)

**Comment by jworm7** [comment]
I'm having the same issue. @aaustin, adding sdk : api to the deeplink data didnt help.

**Comment by aaustin** [comment]
Hmm - Let me look into this.

**Comment by jworm7** [comment]
I was able to find this issue on github, not sure if this helps: https://github.com/BranchMetrics/Deferred-Deep-Linking-Public-API/issues/11 <https://github.com/BranchMetrics/Deferred-Deep-Linking-Public-API/issues/11>


Julien Wormser
Founder - CTO | Servy <http://www.servyapp.com/> 
Twitter <https://twitter.com/ServyApp> | AngelList <https://angel.co/servy> | Facebook <https://www.facebook.com/ServyApp> | LinkedIn <https://www.linkedin.com/in/julienwormser1>

**Comment by aaustin** [comment]
@jworm7 I just tried a curl from my terminal on a test app which has universal links enabled on the dashboard. It correctly returned a Universal Link. Can you share your app key and curl structure?

**Comment by jworm7** [comment]
So I just discovered that I was able to get a Universal Link if I don't include a custom link label. Is there a way to have a custom link label and a Universal Link?

**Comment by aaustin** [comment]
Ahh - you bet. Aliased links will work as universal links *if* you use a custom link domain. You just have to register a subdomain DNS as instructed on our settings page: https://dashboard.branch.io/#/settings/link
