### ISSUE TITLE
Broken Formatting for Referral Code Documentation

### ISSUE THREAD

**Issue by nickbarnwell** [BranchMetrics/Deferred-Deep-Linking-Public-API#5]
From ["Get or Create a Branch Referral Code"](https://github.com/BranchMetrics/Branch-Public-API#getcreate-a-branch-referral-code) onwards all the "Returns" blocks aren't insufficiently indented or not demarcated with code blocks, and render as plaintext:
![screen shot 2015-05-01 at 2 27 08 pm](https://cloud.githubusercontent.com/assets/380810/7437651/3bacb00a-f00e-11e4-9985-6f4d545db45a.png)

Happy to fix myself if you'll accept a PR.

**Comment by Sarkar** [comment]
Hey Nick! We'd be happy to accept a PR - sorry for the crappy formatting :(
